#pragma config(Motor,  port2,           RightMotor,    tmotorVex269, openLoop)
#pragma config(Motor,  port4,           LeftMotor,     tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
     //motor[RightMotor] = 127;
     //motor[LeftMotor]  = 127;
     //wait1Msec(10000);


  //int drivePower = 50;

  // ClearTimer(T1);

  // while(time1[T1] < 2000)
  // {
  //   motor[RightMotor] = 255;
  //   motor[LeftMotor]  = 255;
  // }


  // ClearTimer(T1);
  // while(time1[T1] < 500)
  // {
  //   motor[RightMotor] = 127;
  //   motor[LeftMotor]  = 127;
  // }

  // ClearTimer(T1);
  // while(time1[T1] < 2000)
  // {
  //   motor[RightMotor] = 127 + drivePower;
  //   motor[LeftMotor]  = 127 - drivePower;
  // }

  // motor[RightMotor] = 127;
  // motor[LeftMotor]  = 127;


	while(true)
	{
		  motor[RightMotor]   = vexRT[Ch3];       // up = CW
      motor[LeftMotor]  = -vexRT[Ch2];      // up = CCW


      motor[RightMotor] = 127;
      motor[LeftMotor]  = 127;
      wait1Msec(10000);

      motor[RightMotor] = 0;
      motor[LeftMotor]  = 0;
      wait1Msec(1000);

      motor[RightMotor] = -127;
      motor[LeftMotor]  = -127;
      wait1Msec(10000);
  }

}
