#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           RightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port6,           ArmMotor,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void driveMotors(int leftSpeed, int rightSpeed)
{
	motor[LeftMotor]  = leftSpeed;
	motor[RightMotor] = -rightSpeed;
}

void teleop()
{
	driveMotors(vexRT[Ch3], vexRT[Ch2]);

	int armSpeed = 0;
	if(vexRT[Btn5U])
	{
		armSpeed = 127;
	}
	else if(vexRT[Btn5D])
	{
		armSpeed = -127;
	}
	moveArm(armSpeed);
}

void autonomous()
{
	//insert auton mode
}


task main()
{
	while(true)
	{
		teleop();
	}


}
