#pragma config(Motor,  port1,           LeftDriveA,    tmotorVex269, openLoop)
#pragma config(Motor,  port2,           LeftDriveB,    tmotorVex269, openLoop)
#pragma config(Motor,  port4,           RightDriveA,   tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port5,           RightDriveB,   tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port6,           Flipper,       tmotorVex269, openLoop)
#pragma config(Motor,  port7,           FlipperB,      tmotorVex269, openLoop)
#pragma config(Motor,  port8,           ScissorLiftA,  tmotorVex269, openLoop)
#pragma config(Motor,  port9,           ScissorLiftB,  tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setDriveLeftRight(int aLeft, int aRight)
{
  //motor[LeftDriveA]   = aLeft;
  //motor[LeftDriveB]   = aLeft;
  //motor[RightDriveA]  = aRight;
  //motor[RightDriveB]  = aRight;


  motor[LeftDriveA]   = aLeft;
  motor[LeftDriveB]   = aLeft;
  motor[RightDriveA]  = aRight;
  motor[RightDriveB]  = aRight;
}

void controlScissorLift()
{
    if(vexRT[Btn6D])
    {
    	motor[ScissorLiftA] = -127;
    	motor[ScissorLiftB] = -127;
    }
    else if(vexRT[Btn6U])
    {
    	motor[ScissorLiftA] = 127;
    	motor[ScissorLiftB] = 127;
    }
    else
    {
    	motor[ScissorLiftA] = 0;
    	motor[ScissorLiftB] = 0;
    }
}

void controlFlipper()
{
    if(vexRT[Btn6D])
    {
    	motor[Flipper]  = -127;
    	motor[FlipperB] = -127;
    }
    else if(vexRT[Btn6U])
    {
    	motor[Flipper]  = 127;
    	motor[FlipperB] = 127;
    }
    else
    {
    	motor[Flipper]  = 0;
    	motor[FlipperB] = 0;
    }
}


void stopDriveMotors()
{
		stopMotor(RightDriveA);
		stopMotor(RightDriveB);
	  stopMotor(LeftDriveA);
		stopMotor(LeftDriveB);
}

task main()
{

		untilButtonPress(vexRT[Btn8U]);


		setDriveLeftRight(90, 100);
	  waitInMilliseconds(3000);

    stopDriveMotors();
		waitInMilliseconds(100);

		setDriveLeftRight(100, -100);
		waitInMilliseconds(600);

		stopDriveMotors();
		waitInMilliseconds(100);

		setDriveLeftRight(90, 100);
		waitInMilliseconds(1000);

		stopDriveMotors();

	//while (true)
	{
		  //setDriveLeftRight(vexRT[Ch3], vexRT[Ch2]);
      //controlFlipper();
      //controlScissorLift();


    //motor[LeftDriveA]   = vexRT[Ch3];
    //motor[LeftDriveB]   = vexRT[Ch3];
    //motor[RightDriveA]  = vexRT[Ch2];
    //motor[RightDriveB]  = vexRT[Ch2];
	}
}
