#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           RightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port6,           ArmMotor,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void driveMotors(int leftSpeed, int rightSpeed)
{
	motor[LeftMotor]   =  leftSpeed;      // up = CW
	motor[RightMotor]  =  -rightSpeed;    // up = CCW
}

void moveArm(int aSpeed)
{
	motor[ArmMotor] = aSpeed;
}


void teleop()
{
	driveMotors(vexRT[Ch3], vexRT[Ch2]);

	int armSpeed = 0;
	if(vexRT[Btn5U])
	{
		armSpeed = 127;
	}
	else if(vexRT[Btn5D])
	{
		armSpeed = -127;
	}
	moveArm(armSpeed);
}

void autonDriveStraight(int aMilli)
{
	driveMotors(100, 105);
	wait1Msec(aMilli);
	driveMotors(0, 0);
	wait1Msec(5);
}


void twoBallAuton()
{
	wait1Msec(1500);


	driveMotors(-100, -105); //drive backwards (3seconds)
	wait1Msec(2300);
	driveMotors(0, 0);
	wait1Msec(5);

	driveMotors(100,105); //drive forwards (1second)
	wait1Msec(1500);
	driveMotors(0,0);
	wait1Msec(5);

	driveMotors(50,-55);//Turn toward second ball (Red Side)
	wait1Msec(2000);											//NOTE:driveMotors(100,-105); wait1Msec(2000); is about 90 degrees clockwise
	driveMotors(0,0);
	wait1Msec(5);

	driveMotors(-100,-105);//Move towards ball
	wait1Msec(2300);
	driveMotors(0,0);
	wait1Msec(5);
}
void middleZoneAuton()
{
	//drive forward for 4 seconds

	driveMotors(-100, -105);
	wait1Msec(3000);
	driveMotors(0, 0);
	wait1Msec(5);


	driveMotors(0, 0);

	//Pretend to wait for picking up ball
	wait1Msec(2000);
}

void skillChallengeMiddleAuto()
{

}

void skillChallengeBackAuto()
{

}

void autonomous()
{
	//middleZoneAuton();
  twoBallAuton();
}

task main()
{
	while(true)
	{
		teleop();
	}

	//autonomous();

}
