#pragma config(Motor,  port2,           leftServo,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           rightServo,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int x = 0;

	while(x == 0)
	{
		motor[leftServo] = 127;
		motor[rightServo] = 127;
		wait1Msec(50);
		x = 1;
	}

}
