#pragma config(Motor,  port2,           LeftDrive,     tmotorVex393, openLoop)
#pragma config(Motor,  port5,           RightDrive,    tmotorVex393, openLoop)
#pragma config(Motor,  port7,           ForkliftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port8,           ScissorDown,   tmotorVex393, openLoop)
#pragma config(Motor,  port9,           ScissorUp,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void driveMotors(int leftSpeed, int rightSpeed)
{
	motor[LeftDrive]   =  leftSpeed;      // up = CW
	motor[RightDrive]  =  -rightSpeed;    // up = CCW
}

void controlScissors()
{
	if(vexRT[Btn8U])
	{
		motor[ScissorUp] = 127;
	}
	else if(vexRT[Btn8D])
	{
		motor[ScissorUp] = -50;
	}
	else
	{
		motor[ScissorUp] = 0;
	}

	if(vexRT[Btn7D])
	{
		motor[ScissorDown] = 50;
	}
	else if(vexRT[Btn7U])
	{
		motor[ScissorDown] = -127;
	}
	else
	{
		motor[ScissorDown] = 0;
	}

}

void forklift()
{
	if(vexRT[Btn6U])
	{
		motor[ForkliftMotor] = 127;
	}
	else if(vexRT[Btn6D])
	{
		motor[ForkliftMotor] = -127;
	}
	else
	{
		motor[ForkliftMotor] = 0;
	}
}

void teleop()
{
	driveMotors(vexRT[Ch3], vexRT[Ch2]);
	controlScissors();
	forklift();
}

void singleBallStraightAuto()
{
	//drive forward for 4 seconds
	driveMotors(100, 105);
	wait1Msec(900);
	driveMotors(0, 0);
	wait1Msec(5);

	//driveMotors(-120,125); //TURNS LEFT 120?
	//wait1Msec(5000);
	//driveMotors(0,0);
	//wait1Msec(5);

	//driveMotors(-100,-105); BACKWARDS
	//wait1Msec(2300);
	//driveMotors(0,0);
	//wait1Msec(5);

	driveMotors(0, 0);
}



/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	singleBallStraightAuto();

	motor[ScissorUp]=(-100);
	wait1Msec(2000);
	motor[ScissorUp]=(0);
	wait1Msec(5);

	driveMotors(100,105);
	wait1Msec(100);
	driveMotors(0,0);
	wait1Msec(5);

	driveMotors(-100,-105);
	wait1Msec(600);
	driveMotors(0,0);
	wait1Msec(5);

	motor[ScissorUp]=(100);
	wait1Msec(2000);
	motor[ScissorUp]=(0);
	wait1Msec(5);

	//wait1Msec(13000);

  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................
	  // Insert user code here. This is where you use the joystick values to update your motors, etc.
	  // .....................................................................................

	  // UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
	  teleop();
	}
}
